-- FitZone AI platform expansion migration.
-- Run after the existing recommendation-workout-link migration.
-- Safe to re-run for the added columns/tables.

create extension if not exists pgcrypto;

alter table if exists public.nutrition_logs
  add column if not exists fiber_g numeric,
  add column if not exists entry_source text,
  add column if not exists nutrition_confidence text,
  add column if not exists food_items jsonb,
  add column if not exists logged_at timestamptz default now();

create index if not exists nutrition_logs_user_logged_at_idx
  on public.nutrition_logs (user_id, logged_at desc);

create table if not exists public.memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  membership_plan text,
  status text not null default 'active' check (status in ('active','trial','paused','expired','cancelled')),
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id)
);

create index if not exists memberships_status_idx on public.memberships (status);
create index if not exists memberships_user_idx on public.memberships (user_id);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_user_id uuid references auth.users(id) on delete set null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_at_idx on public.admin_audit_logs (created_at desc);
create index if not exists admin_audit_logs_target_user_idx on public.admin_audit_logs (target_user_id, created_at desc);

alter table public.memberships enable row level security;
alter table public.admin_audit_logs enable row level security;

-- Members can read their own membership. Admin writes are performed by the backend
-- with the service key after an explicit admin authorization check.
drop policy if exists memberships_select_own on public.memberships;
create policy memberships_select_own
  on public.memberships for select
  using (auth.uid() = user_id);

drop policy if exists admin_audit_no_direct_member_access on public.admin_audit_logs;
create policy admin_audit_no_direct_member_access
  on public.admin_audit_logs for select
  using (false);

comment on column public.nutrition_logs.food_items is 'Frozen nutrient-calculation inputs for auditability and reproducibility.';
comment on column public.nutrition_logs.entry_source is 'manual or ai_food_parser.';
comment on column public.nutrition_logs.nutrition_confidence is 'high, medium, or low confidence from food/portion matching.';
