import argparse
import json
from pathlib import Path

import joblib
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    f1_score,
    roc_auc_score,
)
from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder


TARGET = "completion_label"

FEATURES = [
    "age",
    "weight_kg",
    "height_cm",
    "workout_days_per_week",
    "preferred_workout_duration",
    "fitness_level",
    "primary_goal",
    "adherence_percentage",
    "weekly_workout_progress",
    "weekly_minute_progress",
    "recent_sessions",
    "recent_active_minutes",
    "nutrition_available",
    "calorie_percentage",
    "protein_percentage",
    "readiness_score",
    "difficulty_preference",
    "recommendation_action",
]

NUMERIC_FEATURES = [
    "age",
    "weight_kg",
    "height_cm",
    "workout_days_per_week",
    "preferred_workout_duration",
    "adherence_percentage",
    "weekly_workout_progress",
    "weekly_minute_progress",
    "recent_sessions",
    "recent_active_minutes",
    "nutrition_available",
    "calorie_percentage",
    "protein_percentage",
    "readiness_score",
    "difficulty_preference",
]

CATEGORICAL_FEATURES = [
    "fitness_level",
    "primary_goal",
    "recommendation_action",
]


def train(input_path, output_dir):
    input_path = Path(input_path)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print("Loading dataset...")
    df = pd.read_csv(input_path)

    required = FEATURES + [TARGET, "user_id"]

    missing = [
        column
        for column in required
        if column not in df.columns
    ]

    if missing:
        raise ValueError(
            f"Missing required columns: {missing}"
        )

    # Never use completion_probability as a feature.
    # It is generated by the synthetic label-generation process
    # and would cause target leakage.
    X = df[FEATURES].copy()
    y = df[TARGET].astype(int)

    print(f"Rows: {len(df)}")
    print(f"Users: {df['user_id'].nunique()}")
    print(
        "Completion rate: "
        f"{y.mean() * 100:.2f}%"
    )

    # Split by user, not random rows.
    # This prevents events from the same user appearing
    # in both training and validation sets.
    splitter = GroupShuffleSplit(
        n_splits=1,
        test_size=0.2,
        random_state=42,
    )

    train_idx, test_idx = next(
        splitter.split(
            X,
            y,
            groups=df["user_id"],
        )
    )

    X_train = X.iloc[train_idx]
    X_test = X.iloc[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

    print()
    print("Train rows:", len(X_train))
    print("Validation rows:", len(X_test))
    print(
        "Train users:",
        df.iloc[train_idx]["user_id"].nunique(),
    )
    print(
        "Validation users:",
        df.iloc[test_idx]["user_id"].nunique(),
    )

    preprocessor = ColumnTransformer(
        transformers=[
            (
                "numeric",
                "passthrough",
                NUMERIC_FEATURES,
            ),
            (
                "categorical",
                OneHotEncoder(
                    handle_unknown="ignore"
                ),
                CATEGORICAL_FEATURES,
            ),
        ]
    )

    model = RandomForestClassifier(
        n_estimators=300,
        max_depth=12,
        min_samples_leaf=4,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1,
    )

    pipeline = Pipeline(
        steps=[
            ("preprocessor", preprocessor),
            ("model", model),
        ]
    )

    print()
    print("Training personalization model...")

    pipeline.fit(X_train, y_train)

    probabilities = pipeline.predict_proba(X_test)[:, 1]
    predictions = (
        probabilities >= 0.5
    ).astype(int)

    metrics = {
        "accuracy": accuracy_score(
            y_test,
            predictions,
        ),
        "balanced_accuracy": balanced_accuracy_score(
            y_test,
            predictions,
        ),
        "f1": f1_score(
            y_test,
            predictions,
        ),
        "roc_auc": roc_auc_score(
            y_test,
            probabilities,
        ),
        "train_rows": len(X_train),
        "validation_rows": len(X_test),
        "train_users": int(
            df.iloc[train_idx]["user_id"].nunique()
        ),
        "validation_users": int(
            df.iloc[test_idx]["user_id"].nunique()
        ),
        "features": FEATURES,
        "target": TARGET,
        "synthetic_data": True,
        "model": "RandomForestClassifier",
    }

    print()
    print("MODEL METRICS")
    print("=============")

    for name, value in metrics.items():
        if isinstance(value, float):
            print(f"{name}: {value:.4f}")
        elif not isinstance(value, list):
            print(f"{name}: {value}")

    print()
    print("Classification report:")
    print(
        classification_report(
            y_test,
            predictions,
            digits=4,
        )
    )

    model_path = (
        output_dir
        / "personalization_completion_model.joblib"
    )

    metadata_path = (
        output_dir
        / "personalization_model_metadata.json"
    )

    joblib.dump(
        pipeline,
        model_path,
    )

    with metadata_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            metrics,
            file,
            indent=2,
        )

    print()
    print("Saved model:")
    print(model_path)

    print("Saved metadata:")
    print(metadata_path)


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        required=True,
    )

    parser.add_argument(
        "--output-dir",
        default="models",
    )

    args = parser.parse_args()

    train(
        args.input,
        args.output_dir,
    )


if __name__ == "__main__":
    main()