import { useEffect, useState } from 'react'

function AIPlan() {
  const [profile, setProfile] = useState(null)
  const [workout, setWorkout] = useState(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState('')

  const token = localStorage.getItem('fitzone_access_token')

  useEffect(() => {
    loadProfile()
  }, [])

  async function loadProfile() {
    try {
      setLoading(true)
      setError('')

      const response = await fetch('http://localhost:5000/api/profile', {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.message || 'Unable to load profile.')
      }

      setProfile(data.profile)
    } catch (error) {
      console.error('Profile loading error:', error)
      setError(error.message || 'Unable to load profile.')
    } finally {
      setLoading(false)
    }
  }

  async function generatePlan() {
    try {
      setGenerating(true)
      setError('')

      const response = await fetch(
        'http://localhost:5000/api/workouts/generate',
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
        }
      )

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.message || 'Unable to generate workout.')
      }

      setWorkout(data.workout)
    } catch (error) {
      console.error('Workout generation error:', error)
      setError(error.message || 'Unable to generate workout.')
    } finally {
      setGenerating(false)
    }
  }

  if (loading) {
    return (
      <div className="page">
        <h1>AI Plan</h1>
        <p>Loading your profile...</p>
      </div>
    )
  }

  if (!profile) {
    return (
      <div className="page">
        <h1>AI Plan</h1>
        <p>{error || 'Profile not found.'}</p>
      </div>
    )
  }

  return (
    <div className="page">
      <h1>Your plan, built around you.</h1>

      <p>
        FitZone AI uses your fitness profile to generate a personalized
        workout.
      </p>

      {error && (
        <p style={{ color: 'red' }}>
          {error}
        </p>
      )}

      <section>
        <h2>Your Profile</h2>

        <p>
          <strong>Goal:</strong>{' '}
          {profile.primary_goal || 'General Fitness'}
        </p>

        <p>
          <strong>Experience:</strong>{' '}
          {profile.fitness_level || 'Beginner'}
        </p>

        <p>
          <strong>Training frequency:</strong>{' '}
          {profile.workout_days_per_week || 3} days / week
        </p>

        <p>
          <strong>Session duration:</strong>{' '}
          {profile.preferred_workout_duration || 45} minutes
        </p>

        <button
          onClick={generatePlan}
          disabled={generating}
        >
          {generating ? 'Generating...' : 'Generate My Plan'}
        </button>
      </section>

      {workout && (
        <section>
          <h2>Generated Workout</h2>

          <h3>{workout.workout_name}</h3>

          <p>
            {workout.workout_type} · {workout.duration_minutes} min ·{' '}
            {workout.difficulty}
          </p>

          <h3>Exercises</h3>

          {workout.exercises?.length > 0 ? (
            <div>
              {workout.exercises.map((exercise, index) => (
                <div key={`${exercise.name}-${index}`}>
                  <strong>
                    {index + 1}. {exercise.name}
                  </strong>

                  <p>
                    {exercise.sets} sets
                    {exercise.repetitions
                      ? ` × ${exercise.repetitions} reps`
                      : ''}
                    {exercise.duration_seconds
                      ? ` × ${exercise.duration_seconds} sec`
                      : ''}
                    {exercise.rest_seconds
                      ? ` · ${exercise.rest_seconds}s rest`
                      : ''}
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <p>No exercises were generated.</p>
          )}

          <p>
            <strong>Generated by:</strong>{' '}
            {workout.metadata?.generated_by || 'FitZone AI'}
          </p>
        </section>
      )}
    </div>
  )
}

export default AIPlan